[package]
name = "limited_string"
version = "0.1.0"
authors = ["Paulo Cabral Sanz <paulosanz@poli.ufrj.br>"]
license = "MIT OR Apache-2.0"

[profile.release]
panic = 'abort'
lto = true

[lib]
name = "limited_string"
crate_type = ["lib", "cdylib", "staticlib"]

[dependencies]
log = { version = "0.4", optional = true }
env_logger = { version = "0.5", optional = true }
serde = { version = "1.0", optional = true }

[features]
nightly = []
logs = ["log", "env_logger"]
serde-traits = ["serde"]

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docs_rs_workaraound"]
features = ["logs", "serde-traits"]
